package bingx

import (
	"encoding/json"

	"github.com/thrasher-corp/gocryptotrader/currency"
	"github.com/thrasher-corp/gocryptotrader/exchanges/orderbook"
	"github.com/thrasher-corp/gocryptotrader/types"
)

// ResponseWrapper represents a common server response wrapper
type ResponseWrapper struct {
	Code      uint64 `json:"code"`
	Msg       string `json:"msg"`
	Retryable int64  `json:"retryable"`
	Data      any    `json:"data"`
}

// ConfigSymbols represents a common symbols used by the market
type ConfigSymbols struct {
	Symbols []*SymbolDetail `json:"symbols"`
}

// SymbolDetail represents a spot symbol detail.
type SymbolDetail struct {
	Symbol            currency.Pair `json:"symbol"`
	MinimumQuantity   float64       `json:"minQty"`
	MaximumQuantity   float64       `json:"maxQty"`
	MinNotional       float64       `json:"minNotional"`
	MaxNotional       float64       `json:"maxNotional"`
	MaxMarketNotional float64       `json:"maxMarketNotional"`
	Status            float64       `json:"status"`
	TickSize          float64       `json:"tickSize"`
	StepSize          float64       `json:"stepSize"`
	APIStateSell      bool          `json:"apiStateSell"`
	APIStateBuy       bool          `json:"apiStateBuy"`
	TimeOnline        int           `json:"timeOnline"`
	OffTime           uint64        `json:"offTime"`
	MaintainTime      uint64        `json:"maintainTime"`
	DisplayName       string        `json:"displayName"`
}

type AutoGenerated struct {
	Code      uint64          `json:"code"`
	Timestamp int64           `json:"timestamp"`
	Data      []SpotTradeInfo `json:"data"`
}

// SpotTradeInfo represents a spot trade infomration detail
type SpotTradeInfo struct {
	ID         uint64     `json:"id"`
	Price      float64    `json:"price"`
	Quantity   float64    `json:"qty"`
	Time       types.Time `json:"time"`
	BuyerMaker bool       `json:"buyerMaker"`
}

// SpotOrderbookDetail represent an orderbook detail of a symbol
type SpotOrderbookDetail struct {
	Bids         orderbook.LevelsArrayPriceAmount `json:"bids"`
	Asks         orderbook.LevelsArrayPriceAmount `json:"asks"`
	Timestamp    types.Time                       `json:"ts"`
	LastUpdateID uint64                           `json:"lastUpdateId"`
}

// SpotCandle represents a spot kine data information
type SpotCandle struct {
	Timestamp types.Time
	Open      float64
	Close     float64
	High      float64
	Low       float64
	Quantity  float64
	CloseTime types.Time
	Amount    float64
}

// UnmarshalJSON deserializes JSON payload into SpotCandle
func (s *SpotCandle) UnmarshalJSON(data []byte) error {
	target := []any{&s.Timestamp, &s.Open, &s.Close, &s.High, &s.Low, &s.Quantity, &s.CloseTime, &s.Amount}
	return json.Unmarshal(data, &target)
}
